### ISSUE TITLE
When initial try fails, retry fails with "unique tmp filename" error

### ISSUE THREAD

**Issue by johnlindquist** [zeit/now-serve#7]
```
C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\dist\bin\ns:116
  throw err;
  ^

Error: Could not get a unique tmp filename, max tries reached
    at _getTmpNameSync (C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\node_modules\tmp\lib\tmp.js:198:9)
    at Object._createTmpDirSync [as dirSync] (C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\node_modules\tmp\lib\tmp.js:328:14)
    at Object.<anonymous> (C:\Users\johnl\AppData\Roaming\npm\node_modules\now-serve\dist\bin\ns:111:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
```

**Comment by leo** [comment]
Would exactly do you mean with "when initial try fails"? How did the first try fail? :blush:

**Comment by purplecones** [comment]
I am getting the same message but error occurs on line 113. Running on MacOS 10.12  

```
/usr/local/lib/node_modules/now-serve/dist/bin/ns:113
  throw err;
  ^

Error: Could not get a unique tmp filename, max tries reached
    at _getTmpNameSync (/usr/local/lib/node_modules/now-serve/node_modules/tmp/lib/tmp.js:197:9)
    at Object._createTmpDirSync [as dirSync] (/usr/local/lib/node_modules/now-serve/node_modules/tmp/lib/tmp.js:327:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/now-serve/dist/bin/ns:103:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```
```
now -v
𝚫 now 0.26.0

ns -v
0.5.1
```

**Comment by purplecones** [comment]
deleting contents of the `/private/var/folders` fixed this for me
