### ISSUE TITLE
failing on windows

### ISSUE THREAD

**Issue by johnlindquist** [zeit/now-serve#8]
Running `ns ./`

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn now ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by leo** [comment]
Does running `now` work fine?

**Comment by johnlindquist** [comment]
yes
